project:
  type: website
  
execute: 
  freeze: auto

website:
  title: "Something Borrowed"
  description: "A free, community-based, wedding item exchange"
  favicon: circle_logo_border.png
  navbar:
    logo: circle_logo_border.png
    logo-alt: "Two horizontal hands, one facing down and one facing up, as if one was giving something to the other"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - icon: slack
        href: https://somethingborrowedx.slack.com/
      - icon: github
        href: https://github.com/katzemily/something_borrowed
  page-footer: This website is built with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html), [{{< fa brands github title="Github" >}}](https://github.com/katzemily/something_borrowed), and [Quarto](https://quarto.org/).
  open-graph: true
  google-analytics: 
    tracking-id: "G-TQKQDERBKE"
  cookie-consent: true
    
format:
  html:
    theme: 
      - lux
      - styles.scss
    toc: true

editor: visual

