project:
  type: website

website:
  title: "Something Borrowed"
  description: "A free, community-based, wedding exchange"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - icon: slack
        href: https://somethingborrowedx.slack.com/
      - icon: github
        href: https://github.com/katzemily/something_borrowed

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

