project:
  type: website

website:
  title: "Something Borrowed"
  description: "A free, community-based, wedding exchange"
  favicon: circle_logo_border.png
  navbar:
    logo: circle_logo_border.png
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - icon: slack
        href: https://somethingborrowedx.slack.com/
      - icon: github
        href: https://github.com/katzemily/something_borrowed
    # background: "#b5ced3"
    # foreground: black
    
format:
  html:
    theme: 
      - lux
      - styles.scss
    # fontcolor: black
    # linkcolor: "#AE78BF"
    # css: styles.css
    toc: true

editor: visual

